# Generated by Django 5.0.2 on 2024-02-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_submissions_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalforensichub',
            name='submissions_authorised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalforensichub',
            name='submissions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalforensichub',
            name='submissions_holding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalforensichub',
            name='submissions_processing',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
