# Generated by Django 5.0.3 on 2024-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_digitalforensichub_submissions_authorised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalforensichub',
            name='submissions_pending',
            field=models.IntegerField(default=0),
        ),
    ]
